name: polymerase
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.10
  - pip
  - setuptools >=64
  - pyyaml
  - cython
  - numpy
  - scipy
  - pysam >=0.19
  - htslib
  - intervaltree
  - pandas
  - samtools
  - pytest
